name: Deploy function layery

on:
  push:
    paths:
      - "nodejs/**"
    branches:
      - master

jobs:
  lambda-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código (puxando arquivos do repo)
        uses: actions/checkout@v2

      - name: Configurando versão do Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Acessando e instalando as deps na pasta da layer
        run: cd nodejs && npm install && cd ..

      - name: Gerando build da pasta com as deps
        run: npm run layer-build

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - run: aws lambda publish-layer-version \\
          --layer-name my-layer \\n --description "My layer" \\n \\
          --license-info "CMIT" \\n --zip-file fileb://nodejs.zip \\n \\
          --compatible-runtimes nodejs20.x nodejs18.x \\n \\
          --compatible-architectures "arm64" "x86_64"
      - run: aws lambda update-function-configuration \\
          --function-name my-function \\n \\
          --layers arn:aws:lambda:us-east-1:266560762267:layer:my-layer:1

