name: Deploy function codee

on:
  push:
    paths:
      - "!nodejs/**"
    branches:
      - master

jobs:
  lambda-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código (puxando arquivos do repo)
        uses: actions/checkout@v2

      - name: Configurando versão do Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalando dependências do projeto
        run: npm ci

      - name: Gerando build do projeto
        run: npm run build

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - run: aws lambda update-function-code --function-name=my-function --zip-file=fileb://dist/index.zip
