name: Deploy functions

on:
  push:
    branches:
      - master

jobs:
  steps-by-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente
        run: |
          npm install
          npm run build
