name: Deploy function

on:
  push:
    paths:
      - "!nodejs/**"
    branches:
      - master

jobs:
  lambda-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código (puxando arquivos do repo)
        uses: actions/checkout@v2

      - name: Configurando versão do Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalando dependências do projeto
        run: npm ci

      - name: Gerando build do projeto
        run: npm run build

      - name: Define variaveis e executa do deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: my-function
          zip_file: dist/index.zip
